/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jrof.test;

import org.w3c.dom.Element;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import java.io.ByteArrayInputStream;

public class Util {
    public static Element fromXML(String xml) throws Exception {
        Element elem = DocumentBuilderFactory.newInstance().newDocumentBuilder()
                .parse(new ByteArrayInputStream(xml.getBytes())).getDocumentElement();

        return elem;
    }
}